### ISSUE TITLE
Регистрация всех членов команды в github

### ISSUE THREAD

**Issue by jehy** [mami-drones/group5-shelf#3]
- [x] [Салямов Эльдар Маратович](mailto:Eldar.salyamov@yandex.ru) [vk](https://vk.com/eldar.salyamov) [gh](https://github.com/EldarSalyamov)
- [x] [Сафин Валерий Олегович](mailto:valerisafi@gmail.com) [vk](https://vk.com/tokyo_fox) [gh](https://github.com/IceLagTun)
- [x] [Чубуков Алексей Сергеевич](mailto:alekseichubukov@gmail.com) [vk](https://vk.com/id214463174) [gh](https://github.com/Chubukov-Aleksey)
- [x] [Пахомов Илья Сергеевич](mailto:iliap387@bk.ru) [vk](https://vk.com/id271437167)  [gh](
https://github.com/gogoli1)
- [x] [Ася Гущина](mailto:photojornal@yandex.ru) [gh](https://github.com/Astraze)

**Comment by Chubukov-Aleksey** [comment]
- [ ] [Салямов Эльдар Маратович](mailto:Eldar.salyamov@yandex.ru) [vk](https://vk.com/eldar.salyamov) [gh](https://github.com/EldarSalyamov)
- [ ] [Пахомов Илья Сергеевич](mailto:iliap387@bk.ru) [vk](https://vk.com/id271437167) gh
- [ ] [Сафин Валерий Олегович](mailto:valerisafi@gmail.com) [vk](https://vk.com/tokyo_fox) [gh](https://github.com/IceLagTun)
- [ ] [Веселов Никита Андреевич](mailto:kit.arhangel@gmail.com) [vk](https://vk.com/truebolshevik) gh
- [ ] [Чубуков Алексей Сергеевич](mailto:alekseichubukov@gmail.com) [vk](https://vk.com/id214463174) [gh](https://github.com/Chubukov-Aleksey)
